apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-booking-deployment
  labels:
    app: ticket-booking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ticket-booking
  template:
    metadata:
      labels:
        app: ticket-booking
    spec:
      containers:
        - name: ticket-booking-container
          image: pavankumar1018/devops-assignment-2-main:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /  # Change from /health to /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /  # Change from /health to /
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 30